openapi: 3.1.0
info:
  title: mobile_garden_api_v1
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /soilReadings:
    get:
      operationId: get-soilReadings
      parameters:
      - explode: true
        in: query
        name: startDate
        required: false
        schema: {}
        style: form
      - explode: true
        in: query
        name: endDate
        required: false
        schema: {}
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SoilReading'
                x-examples:
                  Example 1:
                  - {}
          description: OK
      summary: Your GET endpoint
      tags: []
    post:
      operationId: post-soilReading
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SoilReading'
          description: OK
      summary: ""
  /photos:
    post:
      operationId: post-file
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties: {}
        description: ""
      responses:
        "200":
          description: OK
      summary: ""
components:
  schemas:
    SoilReading:
      example:
        date: ""
        id: ""
        moisture: ""
      properties:
        id: {}
        moisture: {}
        date: {}
      title: SoilReading
      x-stoplight:
        id: fgq2znwp693rs
x-stoplight:
  id: nnacza4i4uacp
