/*
 * mobile_garden_api_v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SoilReading struct {

	Id *interface{} `json:"id,omitempty"`

	Moisture *interface{} `json:"moisture,omitempty"`

	Date *interface{} `json:"date,omitempty"`
}
