/*
 * mobile_garden_api_v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/joho/godotenv"
	sw "github.com/spintronics/mobile_garden/go"
)

func main() {

	if err := godotenv.Load("credentials.env"); err != nil {
		log.Fatal(err)
	}

	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(router.Run(":8080"))
}
